background:
  category: Background
  values:
    blue_bgr:
      name: Blue
      prob: 0.12
      src: img/background/blue.png
    green_bgr:
      name: Cloudy
      prob: 0.12
      src: img/background/Blue.png
    red_bgr:
      name: Red
      prob: 0.12
      src: img/background/Red.png
    gray_bgr:
      name: Gray
      prob: 0.12
      src: img/background/Gray.png
    salmon_bgr:
      name: Salmon
      prob: 0.12
      src: img/background/Salmon.png
    pink_bgr:
      name: Pink
      prob: 0.12
      src: img/background/Pink.png
    purple_bgr:
      name: Purple
      prob: 0.12
      src: img/background/Purple.png
    orange_bgr:
      name: Orange
      prod: 0.12
      src: img/background/Orange.png
    fire_bgr:
      name: Fire
      prob: 0.04
      src: img/background/Fire.png
    space_bgr:
      name: Space
      prob: 0.04
      src: img/background/Space.png
    cloud_bgr:
      name: Cloud
      prob: 0.04
      src: img/background/Cloud.png

skin:
  category: Skin
  values:
    white_skin:
      name: White
      prob: 0.50
      src: img/skin/White.png
    choco_skin:
      name: Choco
      prob: 0.40
      src: img/skin/Choco.png
    strawberry_skin:
      name: Strawberry
      prob: 0.10
      src: img/skin/Strawberry.png

earring:
  category: Earrings
  values:
    gold_earring:
      name: Gold Dangle
      prob: 0.10
      src: img/earrings/Gold_Dangle.png
    silver_earring:
      name: Silver Cuffs
      prob: 0.10
      src: img/earrings/Silver_Cuffs.png
    gold_cuffs:
      name: Gold Cuffs
      prob: 0.10
      src: img/earrings/Gold_Cuffs.png
    silver_dangle:
      name: Silver Dangle
      prob: 0.10
      src: img/earrings/Silver_Dangle.png
    none_ear:
      prob: 0.60
      src: img/earrings/none.png

horns: 
  category: Horns
  values: 
    gray_horns:
      name: Gray Horns
      prob: 0.75
      src: img/horns/Gray.png
    red_horns: 
      name: Red Horns 
      prob: 0.25
      src: img/horns/Red.png

eye:
  category: Eyes
  values:
    black_eyes:
      name: Black
      prob: 0.15
      src: img/eyes/Black.png
    blue_eyes:
      name: Blue
      prob: 0.15
      src: img/eyes/Blue.png
    green_eyes:
      name: Green
      prob: 0.15
      src: img/eyes/Green.png
    pink_eyes:
      name: Pink
      prob: 0.15
      src: img/eyes/Pink.png
    red_eyes:
      name: Red
      prob: 0.15
      src: img/eyes/Red.png
    anime_glasses:
      name: AnimeGlasses
      prob: 0.05
      src: img/eyes/AnimeGlasses.png
    eyepatch:
      name: Eyepatch
      prob: 0.05
      src: img/eyes/Eyepatch.png
    glasses:
      name: Glasses
      prob: 0.05
      src: img/eyes/Glasses.png
    goji_blindfold: 
      name: Goji Blindfold
      prob: 0.05
      src: img/eyes/GojiBlinfold.png
    green_lazers:
      name: Green Lazers
      prob: 0.025
      src: img/eyes/GreenLazers
    red_lazers:
      name: Red Lazers
      prob: 0.025
      src: img/eyes/RedLazers
accesories:
  values: 
     blood_splatter:
       name: Blood Splatter 
       prob: 0.05
       src: img/accesories/BloodSplatter.png
     luffy_hat:
       name: Luffy Hat
       prob: 0.05
       src: img/accesories/LuffyHat.png
     runny_nose:
       name: Runny Nose 
       prob: 0.30
       src: img/accesories/RunnyNose.png
     smoker:
       name: Smoker
       prob: 0.30
       src: img/accesories/Smoker.png
     sprout: 
       name: Sprout 
       prob: 0.30
       src: img/accesories/Sprout.png
    

